<a href="https://colab.research.google.com/github/siribafna/Myocardial-Infarction-Predictions/blob/main/Senior_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
MI_data=pd.read_csv('MI.txt')

In [ ]:
MI_data.describe()

                ID        "AGE"  ...   "P_IM_STEN"     "LET_IS"
count  1700.000000  1692.000000  ...   1700.000000  1700.000000
mean    850.500000    61.856974  ...      0.087059     0.477059
std     490.892045    11.259936  ...      0.282004     1.381818
min       1.000000    26.000000  ...      0.000000     0.000000
25%     425.750000    54.000000  ...      0.000000     0.000000
50%     850.500000    63.000000  ...      0.000000     0.000000
75%    1275.250000    70.000000  ...      0.000000     0.000000
max    1700.000000    92.000000  ...      1.000000     7.000000

[8 rows x 124 columns]

In [ ]:
# count the number of missing values for each column
total_missing = MI_data.isnull().sum()
missing = total_missing > (len(MI_data)*.5)
missing = total_missing[missing]
# get variables with NaN values > 50% of MI_data
print(missing)
missing[1]
# report the results
total_missing.to_csv('out.csv', index=True)

 "IBS_NASL"      1628
 "S_AD_KBRIG"    1076
 "D_AD_KBRIG"    1076
 "KFK_BLOOD"     1696
dtype: int64

In [ ]:
MI_data.drop(missing.index, axis=1)

        ID   "AGE"   "SEX"  ...   "REC_IM"   "P_IM_STEN"   "LET_IS"
0        1    77.0       1  ...          0             0          0
1        2    55.0       1  ...          0             0          0
2        3    52.0       1  ...          0             0          0
3        4    68.0       0  ...          0             0          0
4        5    60.0       1  ...          0             0          0
...    ...     ...     ...  ...        ...           ...        ...
1695  1696    77.0       0  ...          0             0          3
1696  1697    70.0       0  ...          0             0          1
1697  1698    55.0       1  ...          1             0          6
1698  1699    79.0       0  ...          0             0          1
1699  1700    63.0       1  ...          0             0          1

[1700 rows x 120 columns]

In [ ]:
# fill missing values with mean column values
MI_data.fillna(MI_data.mean(), inplace=True)

ID              0
 "AGE"          0
 "SEX"          0
 "INF_ANAM"     0
 "STENOK_AN"    0
               ..
 "DRESSLER"     0
 "ZSN"          0
 "REC_IM"       0
 "P_IM_STEN"    0
 "LET_IS"       0
Length: 124, dtype: int64